const canvas=document.getElementById('radar');
const ctx=canvas.getContext('2d');
const raster=document.createElement('canvas');
const rctx=raster.getContext('2d',{alpha:false});
let paused=false,last=0,simTime=0;
let speed=1,intensity=70,wind=70,storms=[];
const GRID=240,TAU=Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function seed(){storms=Array.from({length:5},(_,i)=>({x:Math.cos(i*1.71+.7)*(.25+Math.random()*.62),y:Math.sin(i*1.71+.7)*(.25+Math.random()*.62),r:.16+Math.random()*.12,p:2+Math.random()*5,phase:Math.random()*TAU,rot:(Math.random()-.5)*.9,age:Math.random()*12,tilt:(Math.random()-.5)*1.4,tornado:Math.random()<.42,tornadoPhase:Math.random()*TAU,tornadoLife:Math.random()*8,seed:Math.random()*1000}));}
seed();
function resize(){const d=devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0);raster.width=GRID;raster.height=GRID}addEventListener('resize',resize);resize();
const el=id=>document.getElementById(id);el('speed').oninput=e=>{speed=+e.target.value;el('speedOut').textContent=speed.toFixed(2)+'×'};el('intensity').oninput=e=>{intensity=+e.target.value;el('intensityOut').textContent=intensity+'%'};el('wind').oninput=e=>{wind=+e.target.value;el('windOut').textContent=compass(wind)+' · '+wind+'°'};el('toggle').onclick=()=>{paused=!paused;el('toggle').textContent=paused?'▶ Reprendre':'❚❚ Pause'};el('reset').onclick=()=>{seed();simTime=0};el('add').onclick=()=>storms.push({x:(Math.random()-.5)*1.65,y:(Math.random()-.5)*1.65,r:.10+Math.random()*.13,p:2+Math.random()*5,phase:Math.random()*TAU,rot:(Math.random()-.5),age:0,tilt:(Math.random()-.5)*1.4,tornado:Math.random()<.6,tornadoPhase:Math.random()*TAU,tornadoLife:0,seed:Math.random()*1000});
function compass(d){return ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSO','SO','OSO','O','ONO','NO','NNO'][Math.round(d/22.5)%16]}
function hash(x,y,s=0){const n=Math.sin(x*127.1+y*311.7+s*74.7)*43758.5453;return n-Math.floor(n)}
function noise2(x,y,s){const x0=Math.floor(x),y0=Math.floor(y),fx=x-x0,fy=y-y0,sx=fx*fx*(3-2*fx),sy=fy*fy*(3-2*fy),a=hash(x0,y0,s),b=hash(x0+1,y0,s),c=hash(x0,y0+1,s),d=hash(x0+1,y0+1,s),u=a+(b-a)*sx,v=c+(d-c)*sx;return u+(v-u)*sy}
function fbm(x,y,s){let v=0,a=.5;for(let i=0;i<4;i++){v+=noise2(x,y,s+i*17)*a;x*=2.03;y*=2.03;a*=.5}return v}
const palette=[[-5,[7,15,20]],[5,[11,47,58]],[15,[22,126,139]],[20,[40,190,177]],[25,[67,198,79]],[30,[139,216,48]],[35,[221,226,43]],[40,[255,211,39]],[45,[255,151,35]],[50,[239,65,43]],[55,[196,35,70]],[60,[158,35,139]],[65,[112,72,190]],[70,[226,226,236]],[75,[255,255,255]]];
function dbzColor(dbz){if(dbz<palette[0][0])return palette[0][1];for(let i=1;i<palette.length;i++){const a=palette[i-1],b=palette[i];if(dbz<=b[0]){const t=(dbz-a[0])/(b[0]-a[0]);return[a[1][0]+(b[1][0]-a[1][0])*t,a[1][1]+(b[1][1]-a[1][1])*t,a[1][2]+(b[1][2]-a[1][2])*t]}}return palette[palette.length-1][1]}
function stormReflectivity(px,py,s,rangeScale,t){const dx=px-s.x,dy=py-s.y,cs=Math.cos(s.tilt),sn=Math.sin(s.tilt),x=dx*cs+dy*sn,y=-dx*sn+dy*cs,ang=Math.atan2(y,x),wob=1+.16*Math.sin(3*ang+s.phase)+.09*Math.sin(7*ang-s.phase*1.7)+.045*Math.sin(13*ang+s.seed),rx=s.r*(1+.08*Math.sin(s.age*.45+s.seed)),texture=fbm(x/rx*3.1+3,y/rx*3.1-2,s.seed)*.32+fbm(x/rx*8,y/rx*8,s.seed+8)*.12,boundary=1+(texture-.18)*.24,q=Math.hypot(x/(rx*1.16),y/(rx*.82))/wob,shape=Math.exp(-Math.pow(q/(1.05*boundary),3.2));let dbz=-7+shape*(31+intensity*.36);for(let j=0;j<4;j++){const a=s.phase*.42+j*1.57+s.seed*.002,d=rx*(.18+.10*Math.sin(s.phase+j*1.8)),cx=Math.cos(a)*d,cy=Math.sin(a)*d,core=Math.exp(-(((x-cx)/(rx*(.18+.025*j)))**2+((y-cy)/(rx*(.14+.02*j)))**2)*1.8);dbz+=core*(9-j*.7)}const plumeAng=s.rot+.65,cp=Math.cos(plumeAng),sp=Math.sin(plumeAng),tx=x*cp+y*sp,ty=-x*sp+y*cp;dbz+=Math.exp(-((tx-rx*.85)/(rx*1.7))**2-(ty/(rx*.5))**2)*9+Math.exp(-((tx+rx*.65)/(rx*1.8))**2-(ty/(rx*.75))**2)*4;if(s.tornado){const hx=rx*.48,hy=-rx*.28;dbz+=Math.exp(-(((x-hx)/(rx*.34))**2+((y-hy)/(rx*.27))**2)*2.1)*10;dbz-=Math.exp(-(((x-rx*.08)/(rx*.23))**2+((y+rx*.08)/(rx*.18))**2)*2.4)*14;dbz+=Math.exp(-(((x-hx*.82)/(rx*.09))**2+((y-hy*.82)/(rx*.09))**2)*3.5)*(7+Math.sin(s.tornadoPhase)*2)}const range=Math.hypot(px,py)*rangeScale;dbz-=Math.max(0,range-.45)*6.5+range*range*.9;return dbz+Math.sin(ang*9+t*.00025+s.seed)*.65}
function renderReflectivity(){const image=rctx.createImageData(GRID,GRID),data=image.data,scale=2.35/GRID,rangeScale=1.55;for(let j=0;j<GRID;j++)for(let i=0;i<GRID;i++){const px=(i+.5-GRID/2)*scale,py=(j+.5-GRID/2)*scale,range=Math.hypot(px,py);let dbz=-9;if(range<.16)dbz+=Math.max(0,10*(1-range/.16))*noise2(i*.08,j*.08,31);const speck=fbm(i*.065,j*.065,91);if(speck>.69&&range<1)dbz=Math.max(dbz,8+(speck-.69)*18);for(const s of storms)dbz=Math.max(dbz,stormReflectivity(px,py,s,rangeScale,simTime));dbz+=noise2(i*.11,j*.11,17)*1.8-.9;const c=dbzColor(dbz),k=(j*GRID+i)*4;data[k]=c[0];data[k+1]=c[1];data[k+2]=c[2];data[k+3]=255}rctx.putImageData(image,0,0)}
function drawRadar(dt){const w=canvas.clientWidth,h=canvas.clientHeight,cx=w/2,cy=h/2,R=Math.min(w,h)*.46;ctx.clearRect(0,0,w,h);ctx.fillStyle='#040b10';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(cx,cy);const ang=(wind-90)*Math.PI/180;for(const s of storms){const move=dt/1000,dx=Math.cos(ang)*s.p*.008,dy=Math.sin(ang)*s.p*.008;s.x+=dx*speed*move;s.y+=dy*speed*move;s.age+=move*speed;s.phase+=move*(.45+s.rot);s.tornadoPhase+=move*1.8;s.tornadoLife+=move;if(Math.hypot(s.x,s.y)>1.22){s.x=-Math.cos(ang)*1.18;s.y=-Math.sin(ang)*1.18;s.age=0;s.tornadoLife=0}if(s.tornado&&s.tornadoLife>9+Math.abs(Math.sin(s.seed))*8)s.tornado=false;if(!s.tornado&&s.age>4&&intensity>56&&Math.sin(s.age*.73+s.seed)>.94)s.tornado=true}renderReflectivity();ctx.imageSmoothingEnabled=false;ctx.globalAlpha=.96;ctx.drawImage(raster,-R,-R,R*2,R*2);ctx.globalAlpha=1;for(let r=.2;r<=1;r+=.2){ctx.beginPath();ctx.arc(0,0,R*r,0,TAU);ctx.strokeStyle=r===1?'rgba(83,147,158,.65)':'rgba(55,105,115,.38)';ctx.lineWidth=r===1?1.4:1;ctx.stroke()}for(let a=0;a<TAU;a+=Math.PI/12){ctx.beginPath();ctx.moveTo(-R*Math.cos(a),-R*Math.sin(a));ctx.lineTo(R*Math.cos(a),R*Math.sin(a));ctx.strokeStyle='rgba(49,91,100,.28)';ctx.lineWidth=1;ctx.stroke()}const sweep=(simTime*.00055*speed+ang)%TAU;ctx.save();ctx.globalCompositeOperation='screen';ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,R,sweep-.018,sweep+.018);ctx.closePath();ctx.fillStyle='rgba(120,225,255,.12)';ctx.fill();ctx.restore();ctx.beginPath();ctx.arc(0,0,3,0,TAU);ctx.fillStyle='#d9faff';ctx.fill();ctx.restore();ctx.fillStyle='#8db3bd';ctx.font='10px ui-monospace,monospace';ctx.fillText('N',cx-4,cy-R-10);ctx.fillText('S',cx-4,cy+R+18);ctx.fillText('O',cx-R-18,cy+3);ctx.fillText('E',cx+R+8,cy+3);drawLegend(cx-R,cy+R+30)}
function drawLegend(x,y){const labels=[10,20,30,40,50,60,70];ctx.font='9px ui-monospace,monospace';ctx.fillStyle='#9ebdc4';ctx.fillText('RÉFLECTIVITÉ dBZ',x,y-6);const bw=Math.min(30,(Math.min(canvas.clientWidth,canvas.clientHeight)*.72)/labels.length);labels.forEach((v,i)=>{const c=dbzColor(v);ctx.fillStyle=`rgb(${c[0]},${c[1]},${c[2]})`;ctx.fillRect(x+i*bw,y,bw,8);ctx.fillStyle='#789ba4';ctx.fillText(v,x+i*bw-2,y+19)})}
function tick(now){const dt=Math.min(100,now-last||16);last=now;if(!paused)simTime+=dt*speed;drawRadar(dt*speed);const sec=Math.floor(simTime/1000);el('clock').textContent=new Date(0,0,0,12,0,sec%60).toTimeString().slice(0,8);el('stormCount').textContent=storms.length;el('cellCount').textContent=storms.length*4;el('maxIntensity').textContent=Math.round(35+intensity*.48)+' dBZ';requestAnimationFrame(tick)}requestAnimationFrame(tick);