const canvas=document.getElementById('radar');
const ctx=canvas.getContext('2d');
const raster=document.createElement('canvas');
const rctx=raster.getContext('2d',{alpha:false});
let paused=false,last=0,simTime=0,renderClock=0,windMap=true;
let speed=1,intensity=70,wind=70,storms=[];
const GRID=96,TAU=Math.PI*2,RADAR_MS=90;
function makeStorm(i=0){const a=i*1.71+.7,rad=.28+Math.random()*.55;return{x:Math.cos(a)*rad,y:Math.sin(a)*rad,r:.18+Math.random()*.11,p:2+Math.random()*5,phase:Math.random()*TAU,rot:(Math.random()-.5)*.9,age:Math.random()*12,tilt:(Math.random()-.5)*1.4,tornado:Math.random()<.52,tornadoPhase:Math.random()*TAU,tornadoLife:Math.random()*8,seed:Math.random()*1000}};
function seed(){storms=Array.from({length:5},(_,i)=>makeStorm(i));}
seed();
function resize(){const d=devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0);raster.width=GRID;raster.height=GRID}addEventListener('resize',resize);resize();
const el=id=>document.getElementById(id);el('speed').oninput=e=>{speed=+e.target.value;el('speedOut').textContent=speed.toFixed(2)+'×'};el('intensity').oninput=e=>{intensity=+e.target.value;el('intensityOut').textContent=intensity+'%'};el('wind').oninput=e=>{wind=+e.target.value;el('windOut').textContent=compass(wind)+' · '+wind+'°';el('windSpeedMap').textContent=windSpeed()+' kt'};el('windToggle').onclick=()=>{windMap=!windMap;el('windToggle').textContent=windMap?'🌬️ Carte des vents : ON':'🌬️ Carte des vents : OFF';el('windToggle').classList.toggle('active',windMap)};el('toggle').onclick=()=>{paused=!paused;el('toggle').textContent=paused?'▶ Reprendre':'❚❚ Pause';renderClock=RADAR_MS};el('reset').onclick=()=>{seed();simTime=0;renderClock=RADAR_MS};el('add').onclick=()=>{storms.push({...makeStorm(),x:(Math.random()-.5)*1.6,y:(Math.random()-.5)*1.6});renderClock=RADAR_MS};
function compass(d){return ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSO','SO','OSO','O','ONO','NO','NNO'][Math.round(d/22.5)%16]}
function windSpeed(){return Math.round(35+intensity*.5+speed*4)}
function hash(x,y,s=0){const n=Math.sin(x*127.1+y*311.7+s*74.7)*43758.5453;return n-Math.floor(n)}
const palette=[[-5,[7,15,20]],[5,[11,47,58]],[15,[22,126,139]],[20,[40,190,177]],[25,[67,198,79]],[30,[139,216,48]],[35,[221,226,43]],[40,[255,211,39]],[45,[255,151,35]],[50,[239,65,43]],[55,[196,35,70]],[60,[158,35,139]],[65,[112,72,190]],[70,[226,226,236]],[75,[255,255,255]]];
const lut=new Uint8Array(86*3);for(let v=-5;v<=80;v++){let c=palette[palette.length-1][1];if(v<=palette[0][0])c=palette[0][1];else for(let n=1;n<palette.length;n++){const a=palette[n-1],b=palette[n];if(v<=b[0]){const q=(v-a[0])/(b[0]-a[0]);c=[a[1][0]+(b[1][0]-a[1][0])*q,a[1][1]+(b[1][1]-a[1][1])*q,a[1][2]+(b[1][2]-a[1][2])*q];break}}lut[(v+5)*3]=c[0];lut[(v+5)*3+1]=c[1];lut[(v+5)*3+2]=c[2]}
function dbzColor(dbz){const v=Math.max(-5,Math.min(80,Math.round(dbz))),k=(v+5)*3;return[lut[k],lut[k+1],lut[k+2]]}
function stormReflectivity(px,py,s,t){const dx=px-s.x,dy=py-s.y,cs=Math.cos(s.tilt),sn=Math.sin(s.tilt),x=dx*cs+dy*sn,y=-dx*sn+dy*cs,ang=Math.atan2(y,x),rx=s.r*(1+.08*Math.sin(s.age*.45+s.seed));const q=Math.hypot(x/(rx*1.18),y/(rx*.82));let dbz=-8+Math.exp(-Math.pow(q,3.0))*(25+intensity*.42);const rearX=-rx*.28,rearY=rx*.05;dbz+=Math.exp(-((x-rearX)*(x-rearX)/(rx*rx*.24)+(y-rearY)*(y-rearY)/(rx*rx*.42))*2.0)*10;const a=s.phase*.35+.9,dx1=rx*.30*Math.cos(a),dy1=rx*.30*Math.sin(a);dbz+=Math.exp(-((x-dx1)*(x-dx1)/(rx*rx*.08)+(y-dy1)*(y-dy1)/(rx*rx*.11))*2.2)*12;const pa=s.rot+.55,cp=Math.cos(pa),sp=Math.sin(pa),tx=x*cp+y*sp,ty=-x*sp+y*cp;dbz+=Math.exp(-((tx-rx*.72)*(tx-rx*.72)/(rx*rx*.22)+(ty+rx*.18)*(ty+rx*.18)/(rx*rx*.10))*2.0)*13;if(s.tornado){const hx=rx*.48,hy=-rx*.16;dbz+=Math.exp(-((x-hx)*(x-hx)/(rx*rx*.08)+(y-hy)*(y-hy)/(rx*rx*.07))*2.5)*13;dbz-=Math.exp(-((x-rx*.30)*(x-rx*.30)/(rx*rx*.035)+(y+rx*.10)*(y+rx*.10)/(rx*rx*.025))*2.8)*17}const notch=Math.exp(-((tx+rx*.05)*(tx+rx*.05)/(rx*rx*.20)+(ty+rx*.05)*(ty+rx*.05)/(rx*rx*.32))*2.0);dbz-=notch*9;const range=Math.hypot(px,py)*1.45;return dbz-Math.max(0,range-.42)*5.0-range*range*.65+Math.sin(ang*7+s.phase+t*.00015+s.seed)*.7}
function renderReflectivity(){const image=rctx.createImageData(GRID,GRID),data=image.data,scale=2.35/GRID;for(let j=0;j<GRID;j++)for(let i=0;i<GRID;i++){const px=(i+.5-GRID/2)*scale,py=(j+.5-GRID/2)*scale;let dbz=-9;for(let k=0;k<storms.length;k++){const v=stormReflectivity(px,py,storms[k],simTime);if(v>dbz)dbz=v}dbz+=hash(i,j,17)*2-1;const c=dbzColor(dbz),k=(j*GRID+i)*4;data[k]=c[0];data[k+1]=c[1];data[k+2]=c[2];data[k+3]=255}rctx.putImageData(image,0,0)}
function updateStorms(dt){const move=dt/1000,ang=(wind-90)*Math.PI/180;for(const s of storms){const dx=Math.cos(ang)*s.p*.008,dy=Math.sin(ang)*s.p*.008;s.x+=dx*speed*move;s.y+=dy*speed*move;s.age+=move*speed;s.phase+=move*(.45+s.rot);s.tornadoPhase+=move*1.8;s.tornadoLife+=move;if(Math.hypot(s.x,s.y)>1.22){s.x=-Math.cos(ang)*1.18;s.y=-Math.sin(ang)*1.18;s.age=0;s.tornadoLife=0}s.r+=Math.sin(s.age*.12+s.seed)*move*.0005;if(s.tornado&&s.tornadoLife>9+Math.abs(Math.sin(s.seed))*8)s.tornado=false;if(!s.tornado&&s.age>4&&intensity>56&&Math.sin(s.age*.73+s.seed)>.94)s.tornado=true}}
function drawWindMap(R){if(!windMap)return;const base=(wind-90)*Math.PI/180,now=simTime*.00035;ctx.save();ctx.globalAlpha=.72;ctx.lineWidth=1.05;ctx.strokeStyle='rgba(135,225,245,.62)';const spacing=Math.max(34,R*.13),extent=R*1.02;for(let y=-extent;y<=extent;y+=spacing){for(let x=-extent;x<=extent;x+=spacing){let px=x,py=y;const bend=Math.sin((x+y)*.018+now)*7;px+=Math.cos(base+Math.PI/2)*bend;py+=Math.sin(base+Math.PI/2)*bend;const len=18+wind*.035,dx=Math.cos(base)*len,dy=Math.sin(base)*len;ctx.beginPath();ctx.moveTo(px-dx*.5,py-dy*.5);ctx.lineTo(px+dx*.5,py+dy*.5);ctx.stroke();const ax=px+dx*.5,ay=py+dy*.5,side=4;ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(ax-dx/len*side-dy/len*side*.55,ay-dy/len*side+dx/len*side*.55);ctx.moveTo(ax,ay);ctx.lineTo(ax-dx/len*side+dy/len*side*.55,ay-dy/len*side-dx/len*side*.55);ctx.stroke()}}ctx.restore();ctx.save();ctx.globalAlpha=.24;ctx.strokeStyle='rgba(160,240,255,.9)';ctx.lineWidth=1;for(let n=0;n<9;n++){const yy=-R*.82+n*R*.2;ctx.beginPath();for(let q=-R;q<=R;q+=24){const curve=Math.sin(q*.018+n*.8+now)*10,wx=q+Math.cos(base+Math.PI/2)*curve,wy=yy+Math.sin(base+Math.PI/2)*curve;if(q===-R)ctx.moveTo(wx,wy);else ctx.lineTo(wx,wy)}ctx.stroke()}ctx.restore()}
function drawRadar(){const w=canvas.clientWidth,h=canvas.clientHeight,cx=w/2,cy=h/2,R=Math.min(w,h)*.46;ctx.clearRect(0,0,w,h);ctx.fillStyle='#040b10';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(cx,cy);ctx.imageSmoothingEnabled=true;ctx.drawImage(raster,-R,-R,R*2,R*2);drawWindMap(R);for(let r=.2;r<=1;r+=.2){ctx.beginPath();ctx.arc(0,0,R*r,0,TAU);ctx.strokeStyle=r===1?'rgba(83,147,158,.65)':'rgba(55,105,115,.38)';ctx.lineWidth=r===1?1.4:1;ctx.stroke()}for(let a=0;a<TAU;a+=Math.PI/12){ctx.beginPath();ctx.moveTo(-R*Math.cos(a),-R*Math.sin(a));ctx.lineTo(R*Math.cos(a),R*Math.sin(a));ctx.strokeStyle='rgba(49,91,100,.28)';ctx.stroke()}const sweep=(simTime*.00055*speed+(wind-90)*Math.PI/180)%TAU;ctx.save();ctx.globalCompositeOperation='screen';ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,R,sweep-.018,sweep+.018);ctx.closePath();ctx.fillStyle='rgba(120,225,255,.12)';ctx.fill();ctx.restore();ctx.beginPath();ctx.arc(0,0,3,0,TAU);ctx.fillStyle='#d9faff';ctx.fill();ctx.restore();ctx.fillStyle='#8db3bd';ctx.font='10px ui-monospace,monospace';ctx.fillText('N',cx-4,cy-R-10);ctx.fillText('S',cx-4,cy+R+18);ctx.fillText('O',cx-R-18,cy+3);ctx.fillText('E',cx+R+8,cy+3);drawLegend(cx-R,cy+R+30)}
function drawLegend(x,y){const labels=[10,20,30,40,50,60,70];ctx.font='9px ui-monospace,monospace';ctx.fillStyle='#9ebdc4';ctx.fillText('RÉFLECTIVITÉ dBZ',x,y-6);const bw=Math.min(30,(Math.min(canvas.clientWidth,canvas.clientHeight)*.72)/labels.length);labels.forEach((v,i)=>{const c=dbzColor(v);ctx.fillStyle=`rgb(${c[0]},${c[1]},${c[2]})`;ctx.fillRect(x+i*bw,y,bw,8);ctx.fillStyle='#789ba4';ctx.fillText(v,x+i*bw-2,y+19)})}
function tick(now){const dt=Math.min(100,now-last||16);last=now;if(!paused){simTime+=dt*speed;updateStorms(dt)}renderClock+=dt;if(renderClock>=RADAR_MS||paused){renderReflectivity();renderClock=0}el('windSpeedMap').textContent=windSpeed()+' kt';drawRadar();const sec=Math.floor(simTime/1000);el('clock').textContent=new Date(0,0,0,12,0,sec%60).toTimeString().slice(0,8);el('stormCount').textContent=storms.length;el('cellCount').textContent=storms.length*2;el('maxIntensity').textContent=Math.round(35+intensity*.48)+' dBZ';requestAnimationFrame(tick)}requestAnimationFrame(tick);